### ISSUE TITLE
demo 地址不能访问

### ISSUE THREAD

**Issue by latin-xiao-mao** [YUbuntu0109/vsblog#1]

**Comment by latin-xiao-mao** [comment]
都不看的嘛

**Comment by YUbuntu0109** [comment]
> 都不看的嘛

实在抱歉，最近真心比较忙，忘记查看邮件了📧.  我的云服务器过期了，朋友你本地测试吧！

**Comment by LWJhub** [comment]
你好，我想问一下，我运行后，在浏览器访问地址，但是显示没有没有权限

**Comment by GoogTech** [comment]
> 你好，我想问一下，我运行后，在浏览器访问地址（[http://localhost:8080/user/index），但是显示没有没有权限{"code":401,"msg":"您尚未认证](http://localhost:8080/user/index%EF%BC%89%EF%BC%8C%E4%BD%86%E6%98%AF%E6%98%BE%E7%A4%BA%E6%B2%A1%E6%9C%89%E6%B2%A1%E6%9C%89%E6%9D%83%E9%99%90%7B%22code%22:401,%22msg%22:%22%E6%82%A8%E5%B0%9A%E6%9C%AA%E8%AE%A4%E8%AF%81): 无权操作","data":null}。请问怎么解决

Please Check Local Redis Status.
